// data.js — Pre-loaded seed data: 26 Amazon Storefront staging items

const SEED_PROJECT_NAME = 'Amazon Storefront Inventory';

const CATEGORIES = [
  'Plants & Trees',
  'Rugs',
  'Throw Pillows',
  'Vases',
  'Throw Blankets',
  'Baskets & Trays',
  'Accent Pieces',
];

const SEED_PRODUCTS = [
  // ── Category 1: Plants & Trees ──
  {
    name: 'Faux Olive Tree (6ft)',
    description: 'Kazeila — natural wood trunk, lifelike fruits, adjustable branches. Bestseller.',
    amazonUrl: 'https://www.amazon.com/Kazeila-Artificial-Office-Natural-Lifelike/dp/B0BKRFBSTF',
    imageUrl: 'https://m.media-amazon.com/images/I/61jLeoMWFGL._AC_SL1500_.jpg',
    price: '$50–$70',
    category: 'Plants & Trees',
    status: 'review',
  },
  {
    name: 'Faux Olive Tree (7ft)',
    description: 'LYERSE — 37" branch width, natural-textured trunk. Best for 9ft+ ceilings.',
    amazonUrl: 'https://www.amazon.com/LYERSE-Olive-Trees-Artificial-Indoor/dp/B0DFM2PHFX',
    imageUrl: 'https://m.media-amazon.com/images/I/71Rv+BE1vaL._AC_SL1500_.jpg',
    price: '$60–$80',
    category: 'Plants & Trees',
    status: 'review',
  },
  {
    name: 'Mini Faux Succulent Set (4-Pack)',
    description: 'CADNLY — white ceramic pots, 2.2"W x 3"H. Available in green, pink, purple.',
    amazonUrl: 'https://www.amazon.com/CADNLY-Fake-Succulent-Plant-Set/dp/B09VGNPJ32',
    imageUrl: 'https://m.media-amazon.com/images/I/51chAo1xq0L._AC_SL1001_.jpg',
    price: '$16–$22',
    category: 'Plants & Trees',
    status: 'review',
  },
  {
    name: 'Mini Faux Succulents (Set of 3)',
    description: 'Briful — three ceramic pot styles (smooth, bubble-texture, fluted). Lifelike rosettes.',
    amazonUrl: 'https://www.amazon.com/Briful-Succulents-Plants-Artificial-Realistic/dp/B0DBHD2SJY',
    imageUrl: 'https://m.media-amazon.com/images/I/71Doqc8o+qL._AC_SL1500_.jpg',
    price: '$15–$20',
    category: 'Plants & Trees',
    status: 'review',
  },
  {
    name: 'Faux Banana Tree',
    description: 'Tropical silhouette for modern/eclectic projects. High visual impact in content.',
    amazonUrl: 'https://www.amazon.com/s?k=artificial+banana+tree+indoor',
    imageUrl: '',
    price: '$60–$120',
    category: 'Plants & Trees',
    status: 'review',
  },

  // ── Category 2: Rugs ──
  {
    name: 'Loloi Billie Clay/Sage (BIL-03)',
    description: 'Amber Lewis x Loloi — power-loomed polyester, antique distressed, OEKO-TEX certified.',
    amazonUrl: 'https://www.amazon.com/Amber-Loloi-Billie-Collection-BIL-03/dp/B09GV1HQKM',
    imageUrl: 'https://m.media-amazon.com/images/I/61iPHQHw6AL._AC_SL1080_.jpg',
    price: '$140–$350',
    category: 'Rugs',
    status: 'review',
  },
  {
    name: 'Loloi Billie Denim/Blush (BIL-05)',
    description: 'Amber Lewis x Loloi — cooler tone, denim/blush colorway. Content variety.',
    amazonUrl: 'https://www.amazon.com/Loloi-Billie-Collection-BIL-05-Accent/dp/B09GTXQV3S',
    imageUrl: 'https://m.media-amazon.com/images/I/61OW3fgh3hL._AC_SL1080_.jpg',
    price: '$40–$300',
    category: 'Rugs',
    status: 'review',
  },
  {
    name: 'Loloi Billie Aqua/Rust (BIL-04)',
    description: 'Amber Lewis x Loloi — warmer jewel tones, runner sizes available for hallways.',
    amazonUrl: 'https://www.amazon.com/Loloi-Billie-Collection-BIL-04-Runner/dp/B09GV9GZ56',
    imageUrl: 'https://m.media-amazon.com/images/I/613b1rKTYBL._AC_SL1080_.jpg',
    price: '$40–$300',
    category: 'Rugs',
    status: 'review',
  },
  {
    name: 'Loloi Layla Antique/Moss (LAY-13)',
    description: 'Loloi bestseller on Amazon. Stain-resistant polyester/polypropylene, rich vintage look.',
    amazonUrl: 'https://www.amazon.com/s?k=Loloi+Layla+LAY-13+antique+moss',
    imageUrl: '',
    price: '$30–$250',
    category: 'Rugs',
    status: 'review',
  },
  {
    name: 'Loloi Rug Pad (Cushion Grip)',
    description: 'Felt pad, prevents slipping on hard surfaces. Always upsell with every rug.',
    amazonUrl: 'https://www.amazon.com/s?k=Loloi+rug+pad+cushion+grip',
    imageUrl: '',
    price: '$25–$90',
    category: 'Rugs',
    status: 'review',
  },

  // ── Category 3: Throw Pillows ──
  {
    name: 'Boho Textured Pillow Covers (18x18)',
    description: 'Qupace — white/brown/black striped knit. Covers only, need inserts. Set of 2.',
    amazonUrl: 'https://www.amazon.com/Qupace-Minimalist-Decorative-Knitted-Textured/dp/B0GCF47DQC',
    imageUrl: 'https://m.media-amazon.com/images/I/71npRm51yyL._AC_SL1100_.jpg',
    price: '$14–$18',
    category: 'Throw Pillows',
    status: 'review',
  },
  {
    name: 'Linen Striped Pillow Covers (22x22)',
    description: 'DEZENE — linen-cotton-polyester blend, grey textured stripe. Set of 2.',
    amazonUrl: 'https://www.amazon.com/DEZENE-Farmhouse-Neutral-Textured-Decorative/dp/B0FPQGGVLS',
    imageUrl: 'https://m.media-amazon.com/images/I/91Ol4OrogvL._AC_SL1500_.jpg',
    price: '$15–$20',
    category: 'Throw Pillows',
    status: 'review',
  },
  {
    name: 'Boho Lumbar Pillow Covers (20x12)',
    description: 'QDTTSRY — handmade tassels, jacquard weave. Dusty blue option. Set of 2.',
    amazonUrl: 'https://www.amazon.com/QDTTSRY-Decorative-Textured-Striped-Farmhouse/dp/B0FVLY8X51',
    imageUrl: 'https://m.media-amazon.com/images/I/71fWH46uEwL._AC_SL1500_.jpg',
    price: '$13–$17',
    category: 'Throw Pillows',
    status: 'review',
  },
  {
    name: 'Pillow Inserts (20x20, Set of 2)',
    description: 'MIULEE — down feather, cotton fabric. Used on 5+ JKD projects. Proven quality.',
    amazonUrl: 'https://www.amazon.com/s?k=MIULEE+pillow+insert+20x20',
    imageUrl: '',
    price: '$25–$37',
    category: 'Throw Pillows',
    status: 'review',
  },

  // ── Category 4: Vases ──
  {
    name: 'Ceramic Crackled Vase Set (3-Pack)',
    description: 'Tenvy — 3 sizes (5", 7.6", 10"). Crackled glaze, antique feel. Rubber stoppers.',
    amazonUrl: 'https://www.amazon.com/Multi-Color-Farmhouse-Decorative-Decoration-Mutil-Color-1/dp/B08T7XKW7B',
    imageUrl: 'https://m.media-amazon.com/images/I/71m+Gt+Ln4L._AC_SL1500_.jpg',
    price: '$20–$28',
    category: 'Vases',
    status: 'review',
  },
  {
    name: 'Neutral Boho Matte Vase Set',
    description: 'Soft beige/cream/earthy tones. Smooth matte finish, clean minimalist lines.',
    amazonUrl: 'https://www.amazon.com/Neutral-Ceramic-Decorative-Minimalist-Fireplace/dp/B0GHPDMS1F',
    imageUrl: 'https://m.media-amazon.com/images/I/61Ngt16DV5L._AC_SL1500_.jpg',
    price: '$18–$25',
    category: 'Vases',
    status: 'review',
  },
  {
    name: 'Sullivans Ceramic Jug Vase Set',
    description: 'Glazed crackled antique look, 4–10". Rustic/farmhouse. Great for dried stems.',
    amazonUrl: 'https://www.amazon.com/Sullivans-Decorative-Jugs-Set-Grey/dp/B00WT2VF38',
    imageUrl: 'https://m.media-amazon.com/images/I/71pxOB93j+L._AC_SL1500_.jpg',
    price: '$25–$35',
    category: 'Vases',
    status: 'review',
  },

  // ── Category 5: Throw Blankets ──
  {
    name: 'Chunky Knit Throw (Cream, 50x60)',
    description: 'Bedsure — 100% hand knitted, 5+ lbs. Cream white, photographs beautifully.',
    amazonUrl: 'https://www.amazon.com/Bedsure-Chunky-Knit-Blanket-Throw/dp/B0C6XDGSY5',
    imageUrl: 'https://m.media-amazon.com/images/I/91i1RPkmi4L._AC_SL1500_.jpg',
    price: '$40–$55',
    category: 'Throw Blankets',
    status: 'review',
  },
  {
    name: 'Chenille Throw with Tassels (50x60)',
    description: 'Bedsure — khaki/neutral tone, boho tassels. Lighter weight, more affordable.',
    amazonUrl: 'https://www.amazon.com/Bedsure-Throw-Blanket-Couch-Decorative/dp/B08Z3FTKZJ',
    imageUrl: 'https://m.media-amazon.com/images/I/81ZkDOwYK6L._AC_SL1500_.jpg',
    price: '$20–$30',
    category: 'Throw Blankets',
    status: 'review',
  },

  // ── Category 6: Baskets & Trays ──
  {
    name: 'Seagrass Storage Baskets (Set of 2)',
    description: 'StorageWorks — natural seagrass over iron frame, stackable, wooden handles.',
    amazonUrl: 'https://www.amazon.com/StorageWorks-Storage-Baskets-Decorative-Seagrass/dp/B07MM1J2HX',
    imageUrl: 'https://m.media-amazon.com/images/I/81SuV8-oRQL._AC_SL1500_.jpg',
    price: '$25–$35',
    category: 'Baskets & Trays',
    status: 'review',
  },
  {
    name: 'Seagrass Baskets with Lids (Set of 3)',
    description: 'Americanflat — 3 sizes with lids, handmade in Vietnam. Clean organized look.',
    amazonUrl: 'https://www.amazon.com/Americanflat-Woven-Seagrass-Storage-Baskets/dp/B084GDQ1GW',
    imageUrl: 'https://m.media-amazon.com/images/I/71ZW7e-kuJL._AC_SL1500_.jpg',
    price: '$30–$40',
    category: 'Baskets & Trays',
    status: 'review',
  },
  {
    name: 'Marble Decorative Tray',
    description: 'Anchor piece for surface vignettes. Stack with candle + small plant.',
    amazonUrl: 'https://www.amazon.com/s?k=marble+decorative+tray+small',
    imageUrl: '',
    price: '$20–$40',
    category: 'Baskets & Trays',
    status: 'review',
  },

  // ── Category 7: Accent Pieces ──
  {
    name: 'Coffee Table Books (Design/Architecture)',
    description: '3–4 oversized books. Choose neutral spines. Stack with small object on top.',
    amazonUrl: 'https://www.amazon.com/s?k=coffee+table+books+interior+design',
    imageUrl: '',
    price: '$15–$35 each',
    category: 'Accent Pieces',
    status: 'review',
  },
  {
    name: 'Decorative Candle Holders',
    description: 'Brass or matte black candlestick holders, set of 2–3. Versatile across styles.',
    amazonUrl: 'https://www.amazon.com/s?k=decorative+candlestick+holders+brass',
    imageUrl: '',
    price: '$15–$25',
    category: 'Accent Pieces',
    status: 'review',
  },
  {
    name: 'Decorative Bowl (Wood/Ceramic)',
    description: 'Organic shape, adds warmth. Use for keys, display objects, or standalone.',
    amazonUrl: 'https://www.amazon.com/s?k=decorative+wood+bowl+home+decor',
    imageUrl: '',
    price: '$15–$35',
    category: 'Accent Pieces',
    status: 'review',
  },
  {
    name: 'Decorative Sculpture/Object',
    description: 'Statement piece for shelf/surface styling. Organic or geometric shapes.',
    amazonUrl: 'https://www.amazon.com/s?k=decorative+sculpture+modern+home',
    imageUrl: '',
    price: '$20–$50',
    category: 'Accent Pieces',
    status: 'review',
  },
];

export { SEED_PROJECT_NAME, SEED_PRODUCTS, CATEGORIES };
